[build]
  command = "echo 'No build command needed for static site'"
  publish = "./"
  functions = "functions"

# Route API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA redirect for all other requests
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200