[build]
  command = "echo 'No build command needed for static site'"
  publish = "./"
  functions = "functions"

# Redirect all non-function requests to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200